fix(exercise-9): use `include` rule into `tsconfig`
Error:
- Found 7 errors. Watching for file changes.
error TS6059: File '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-2/scripts.ts' is not under 'rootDir' '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-9/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
error TS6059: File '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-3/scripts.ts' is not under 'rootDir' '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-9/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
error TS6059: File '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-4/scripts.ts' is not under 'rootDir' '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-9/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
error TS6059: File '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-5/scripts.ts' is not under 'rootDir' '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-9/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
error TS6059: File '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-6/scripts.ts' is not under 'rootDir' '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-9/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
error TS6059: File '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-7/scripts.ts' is not under 'rootDir' '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-9/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
error TS6059: File '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-X/scripts.ts' is not under 'rootDir' '/Users/beatrizsmerino/Sites/localhost/typescript-course/exercises/exercise-9/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'

Solution:
- Disable compilation on all other files than axis 9 files.